from __future__ import annotations

from .shared import (
    StyleDNA,
    _POOL_BRUTAL,
    _POOL_CREATIVE,
    _POOL_MINIMAL,
    _POOL_NARRATIVE,
    _layout_weights,
    _make_dna,
)

EXPRESSIVE_STYLE_DNAS: tuple[StyleDNA, ...] = (
    _make_dna(
        style_id="botanical",
        name="植境",
        prompt="自然生态风格，清新安静，轻纹理与植物意象，重视舒适阅读。",
        template_style_hint="preset:botanical creative",
        style_recipe="rounded",
        theme_hint={"primary": "2F5D50", "secondary": "5E8B7E", "accent": "8CBF5A", "light": "E9F2EB", "bg": "F7FBF7"},
        layout_family="organic-balance",
        layout_pool_by_page_type=_POOL_NARRATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_NARRATIVE,
            content={
                "content-showcase": 4,
                "content-two-column": 2,
                "content-icon-rows": 3,
                "content-timeline": 1,
            },
            summary={"summary-thankyou": 3, "summary-cta": 2, "summary-split": 2},
        ),
        typography_profile={"title_font": "Palatino Linotype", "body_font": "Garamond"},
        density_profile="airy",
        shape_language="soft-organic",
        decoration_policy="light-texture",
        visual_strategy_profile="imagery-led",
        tone_keywords=("nature", "eco", "wellness"),
    ),
    _make_dna(
        style_id="wabi-sabi",
        name="侘寂",
        prompt="侘寂风格，低饱和质朴、留白克制，强调材质感与东方审美。",
        template_style_hint="preset:wabi-sabi soft balanced",
        style_recipe="soft",
        theme_hint={"primary": "4A3F35", "secondary": "7B6D5D", "accent": "B08B67", "light": "EDE6DE", "bg": "F7F3ED"},
        layout_family="asymmetric-quiet",
        layout_pool_by_page_type=_POOL_MINIMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_MINIMAL,
            content={
                "content-showcase": 3,
                "content-two-column": 3,
                "content-comparison": 2,
            },
            section={"section-center": 3, "section-split": 1},
        ),
        typography_profile={"title_font": "Georgia", "body_font": "Calibri"},
        density_profile="airy",
        shape_language="matte-imperfect",
        decoration_policy="texture-subtle",
        visual_strategy_profile="negative-space",
        tone_keywords=("wabi", "zen", "humanities"),
    ),
    _make_dna(
        style_id="memphis",
        name="孟菲斯",
        prompt="孟菲斯风格，活泼几何、强节奏、图形化，突出创意与年轻感。",
        template_style_hint="preset:memphis creative marketing",
        style_recipe="rounded",
        theme_hint={"primary": "111111", "secondary": "2A2A2A", "accent": "FF3D81", "light": "FFE66D", "bg": "FFF6EC"},
        layout_family="geo-pop",
        layout_pool_by_page_type=_POOL_CREATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_CREATIVE,
            content={
                "content-icon-rows": 4,
                "content-showcase": 3,
                "content-comparison": 2,
                "content-timeline": 2,
            },
            toc={"toc-cards": 4, "toc-grid": 3, "toc-sidebar": 1},
        ),
        typography_profile={"title_font": "Trebuchet MS", "body_font": "Arial"},
        density_profile="balanced",
        shape_language="geometry-contrast",
        decoration_policy="decorative-allowed",
        visual_strategy_profile="shape-burst",
        tone_keywords=("memphis", "playful", "youth"),
    ),
    _make_dna(
        style_id="constructivism",
        name="构成主义",
        prompt="构成主义风格，高对比、斜切与非对称构图，强调力量感。",
        template_style_hint="preset:constructivism brutal sharp data",
        style_recipe="sharp",
        theme_hint={"primary": "111111", "secondary": "2E2E2E", "accent": "E10600", "light": "F5F5F5", "bg": "FFF8E1"},
        layout_family="poster-diagonal",
        layout_pool_by_page_type=_POOL_BRUTAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_BRUTAL,
            content={
                "content-comparison": 4,
                "content-showcase": 3,
                "content-two-column": 2,
                "content-timeline": 3,
            },
            section={"section-accent-block": 4, "section-split": 3},
        ),
        typography_profile={"title_font": "Arial", "body_font": "Arial"},
        density_profile="dense",
        shape_language="hard-edges",
        decoration_policy="poster-strong",
        visual_strategy_profile="directional-flow",
        tone_keywords=("constructivism", "manifesto", "contrast"),
    ),
    _make_dna(
        style_id="neo-brutalism",
        name="新粗野主义",
        prompt="新粗野主义风格，直接硬朗、实验感强，粗体与块面优先。",
        template_style_hint="preset:neo-brutalism brutal sharp",
        style_recipe="sharp",
        theme_hint={"primary": "0A0A0A", "secondary": "1D1D1D", "accent": "00D1FF", "light": "F4F4F4", "bg": "FFFFFF"},
        layout_family="raw-block",
        layout_pool_by_page_type=_POOL_BRUTAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_BRUTAL,
            content={
                "content-showcase": 4,
                "content-comparison": 4,
                "content-two-column": 2,
                "content-timeline": 1,
            },
            toc={"toc-sidebar": 4, "toc-grid": 2},
        ),
        typography_profile={"title_font": "Arial", "body_font": "Arial"},
        density_profile="compact",
        shape_language="thick-outline",
        decoration_policy="raw-ui",
        visual_strategy_profile="impact-first",
        tone_keywords=("brutalism", "raw", "experimental"),
    ),
    _make_dna(
        style_id="8bit",
        name="8-bit",
        prompt="像素复古风格，电子游戏界面语言，方块图形与像素边框。",
        template_style_hint="preset:8bit retro pixel",
        style_recipe="sharp",
        theme_hint={"primary": "1A1A1A", "secondary": "3A3A3A", "accent": "00E676", "light": "F9D65C", "bg": "F5F7FF"},
        layout_family="pixel-grid",
        layout_pool_by_page_type=_POOL_CREATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_CREATIVE,
            content={
                "content-icon-rows": 4,
                "content-two-column": 3,
                "content-timeline": 2,
                "content-showcase": 2,
            },
            toc={"toc-cards": 3, "toc-grid": 3, "toc-sidebar": 1},
        ),
        typography_profile={"title_font": "Arial", "body_font": "Arial"},
        density_profile="compact",
        shape_language="square-pixel",
        decoration_policy="retro-ui",
        visual_strategy_profile="icon-heavy",
        tone_keywords=("pixel", "retro", "game"),
    ),
    _make_dna(
        style_id="electro-pop",
        name="流行电子",
        prompt="电子潮流风格，霓虹发光、未来感和高冲击构图。",
        template_style_hint="preset:electro-pop premium brand luxury",
        style_recipe="pill",
        theme_hint={"primary": "120024", "secondary": "3A0B63", "accent": "FF00C8", "light": "00E5FF", "bg": "0E0A1F"},
        layout_family="neon-stage",
        layout_pool_by_page_type=_POOL_CREATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_CREATIVE,
            content={
                "content-showcase": 4,
                "content-timeline": 3,
                "content-icon-rows": 2,
                "content-comparison": 2,
            },
            section={"section-split": 4, "section-accent-block": 2, "section-center": 1},
        ),
        typography_profile={"title_font": "Arial", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="glow-rounded",
        decoration_policy="neon-accent",
        visual_strategy_profile="hero-visual",
        tone_keywords=("electro", "neon", "future"),
    ),
    _make_dna(
        style_id="geo-bold",
        name="几何粗体",
        prompt="几何粗体风格，块面结构与大字号标题，强调识别度。",
        template_style_hint="preset:geo-bold sharp data",
        style_recipe="sharp",
        theme_hint={"primary": "111111", "secondary": "2B2B2B", "accent": "FF6B00", "light": "E8F0FF", "bg": "FFFFFF"},
        layout_family="bold-geometry",
        layout_pool_by_page_type=_POOL_BRUTAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_BRUTAL,
            content={
                "content-comparison": 4,
                "content-two-column": 3,
                "content-showcase": 2,
                "content-timeline": 2,
            },
            toc={"toc-grid": 3, "toc-sidebar": 2},
        ),
        typography_profile={"title_font": "Arial", "body_font": "Arial"},
        density_profile="balanced",
        shape_language="block-geometry",
        decoration_policy="high-contrast",
        visual_strategy_profile="headline-dominant",
        tone_keywords=("geometric", "bold", "graphic"),
    ),
    _make_dna(
        style_id="morandi",
        name="莫兰迪",
        prompt="莫兰迪风格，低饱和柔和配色，克制优雅，文艺舒缓。",
        template_style_hint="preset:morandi soft balanced",
        style_recipe="soft",
        theme_hint={"primary": "6E6A67", "secondary": "8F8A86", "accent": "BCA89F", "light": "E8E2DC", "bg": "F7F4F1"},
        layout_family="muted-editorial",
        layout_pool_by_page_type=_POOL_MINIMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_MINIMAL,
            content={
                "content-showcase": 3,
                "content-two-column": 3,
                "content-comparison": 2,
            },
            summary={"summary-thankyou": 3, "summary-split": 2},
        ),
        typography_profile={"title_font": "Palatino Linotype", "body_font": "Garamond"},
        density_profile="airy",
        shape_language="soft-muted",
        decoration_policy="subtle-gradient",
        visual_strategy_profile="calm-rhythm",
        tone_keywords=("morandi", "elegant", "art"),
    ),
    _make_dna(
        style_id="emotional-flow",
        name="感性流动",
        prompt="感性流动风格，柔雾氛围、曲线与半透明层次，强调情绪表达。",
        template_style_hint="preset:emotional-flow creative rounded",
        style_recipe="rounded",
        theme_hint={"primary": "5A4E7C", "secondary": "7E6FAE", "accent": "F08AA6", "light": "F5EAF3", "bg": "FFF7FB"},
        layout_family="fluid-narrative",
        layout_pool_by_page_type=_POOL_NARRATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_NARRATIVE,
            content={
                "content-showcase": 4,
                "content-timeline": 3,
                "content-two-column": 2,
                "content-icon-rows": 2,
            },
            toc={"toc-cards": 3, "toc-list": 2, "toc-sidebar": 1},
        ),
        typography_profile={"title_font": "Palatino Linotype", "body_font": "Garamond"},
        density_profile="airy",
        shape_language="curved-organic",
        decoration_policy="soft-glow",
        visual_strategy_profile="storytelling-flow",
        tone_keywords=("emotional", "flow", "story"),
    ),
    _make_dna(
        style_id="cinema-minimal",
        name="影院极简",
        prompt="影院极简风格，低照度电影感、光影聚焦、深邃克制。",
        template_style_hint="preset:cinema-minimal soft balanced",
        style_recipe="soft",
        theme_hint={"primary": "F2F2F2", "secondary": "BFBFBF", "accent": "F5C16C", "light": "2A2A2A", "bg": "111111"},
        layout_family="cinematic-focus",
        layout_pool_by_page_type=_POOL_MINIMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_MINIMAL,
            content={
                "content-showcase": 4,
                "content-two-column": 2,
                "content-comparison": 2,
            },
            cover={"cover-center": 3, "cover-asymmetric": 1},
        ),
        typography_profile={"title_font": "Georgia", "body_font": "Calibri"},
        density_profile="airy",
        shape_language="light-beam",
        decoration_policy="shadow-depth",
        visual_strategy_profile="spotlight-hero",
        tone_keywords=("cinema", "movie", "dark"),
    ),
)
