from __future__ import annotations

from .shared import (
    StyleDNA,
    _POOL_GRID_FORMAL,
    _POOL_MINIMAL,
    _POOL_NARRATIVE,
    _POOL_RESEARCH,
    _layout_weights,
    _make_dna,
)

INSTRUCTIONAL_STYLE_DNAS: tuple[StyleDNA, ...] = (
    _make_dna(
        style_id="minimal-teaching",
        name="简约教学",
        prompt="传统教学课件风格，结构清晰、层级明确、稳定统一、便于讲授。",
        template_style_hint="preset:minimal-teaching education training",
        style_recipe="soft",
        theme_hint={"primary": "1F3A5F", "secondary": "4E6A8E", "accent": "2E86DE", "light": "E9EEF5", "bg": "F7FAFC"},
        layout_family="classroom-structured",
        layout_pool_by_page_type=_POOL_GRID_FORMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_GRID_FORMAL,
            content={
                "content-two-column": 4,
                "content-stat-callout": 3,
                "content-comparison": 2,
                "content-showcase": 1,
            },
            toc={"toc-list": 3, "toc-grid": 2, "toc-sidebar": 1},
        ),
        typography_profile={"title_font": "Cambria", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="rounded-calm",
        decoration_policy="minimal-instructional",
        visual_strategy_profile="diagram-first",
        tone_keywords=("education", "training", "clarity"),
    ),
    _make_dna(
        style_id="academic",
        name="学术",
        prompt="学术风格，理性、规范、清晰，强调研究表达、逻辑结构与图表可读性。",
        template_style_hint="preset:academic report data authority",
        style_recipe="sharp",
        theme_hint={"primary": "1F2937", "secondary": "4B5563", "accent": "2563EB", "light": "E5E7EB", "bg": "F9FAFB"},
        layout_family="research-grid",
        layout_pool_by_page_type=_POOL_RESEARCH,
        layout_weights_by_page_type=_layout_weights(
            _POOL_RESEARCH,
            content={
                "content-stat-callout": 4,
                "content-two-column": 3,
                "content-timeline": 2,
                "content-comparison": 2,
            },
            summary={"summary-takeaways": 4, "summary-split": 2, "summary-cta": 1},
        ),
        typography_profile={"title_font": "Georgia", "body_font": "Calibri"},
        density_profile="dense",
        shape_language="line-precision",
        decoration_policy="journal-clean",
        visual_strategy_profile="evidence-priority",
        tone_keywords=("research", "academic", "thesis"),
    ),
    _make_dna(
        style_id="minimal",
        name="极简",
        prompt="极简风格，干净克制，突出留白、层级和信息节奏，减少装饰。",
        template_style_hint="preset:minimal balanced",
        style_recipe="soft",
        theme_hint={"primary": "1A1A1A", "secondary": "666666", "accent": "3B82F6", "light": "EDEDED", "bg": "FFFFFF"},
        layout_family="whitespace-editorial",
        layout_pool_by_page_type=_POOL_MINIMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_MINIMAL,
            content={
                "content-two-column": 4,
                "content-comparison": 3,
                "content-showcase": 2,
            },
            summary={"summary-split": 3, "summary-thankyou": 2},
        ),
        typography_profile={"title_font": "Trebuchet MS", "body_font": "Calibri"},
        density_profile="airy",
        shape_language="thin-subtle",
        decoration_policy="strict-minimal",
        visual_strategy_profile="focus-block",
        tone_keywords=("minimal", "clean", "quiet"),
    ),
    _make_dna(
        style_id="professional",
        name="专业",
        prompt="专业商务科技风格，沉稳正式，模块化表达，强调可信度。",
        template_style_hint="preset:professional finance report authority",
        style_recipe="sharp",
        theme_hint={"primary": "0B1F3A", "secondary": "1E3A5F", "accent": "00A3FF", "light": "E8EEF5", "bg": "F4F7FB"},
        layout_family="enterprise-modular",
        layout_pool_by_page_type=_POOL_GRID_FORMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_GRID_FORMAL,
            content={
                "content-stat-callout": 4,
                "content-two-column": 3,
                "content-showcase": 2,
                "content-comparison": 2,
            },
            toc={"toc-grid": 3, "toc-sidebar": 2, "toc-list": 2},
        ),
        typography_profile={"title_font": "Cambria", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="modular-solid",
        decoration_policy="low-gloss-tech",
        visual_strategy_profile="data-callout",
        tone_keywords=("business", "enterprise", "strategy"),
    ),
    _make_dna(
        style_id="nordic-research",
        name="北欧研究",
        prompt="北欧研究风格，理性自然，清爽网格与低干扰背景。",
        template_style_hint="preset:nordic-research education",
        style_recipe="soft",
        theme_hint={"primary": "223344", "secondary": "4A5F70", "accent": "5FA8D3", "light": "E8EEF2", "bg": "F7FAFC"},
        layout_family="scandi-grid",
        layout_pool_by_page_type=_POOL_RESEARCH,
        layout_weights_by_page_type=_layout_weights(
            _POOL_RESEARCH,
            content={
                "content-two-column": 3,
                "content-stat-callout": 3,
                "content-timeline": 2,
                "content-comparison": 2,
            },
            section={"section-center": 3, "section-accent-block": 1},
        ),
        typography_profile={"title_font": "Cambria", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="clean-functional",
        decoration_policy="low-noise",
        visual_strategy_profile="information-balanced",
        tone_keywords=("nordic", "scandi", "research"),
    ),
    _make_dna(
        style_id="rational-blue",
        name="理性蓝调",
        prompt="理性蓝调风格，冷静专业，强调分析结构与科技可信感。",
        template_style_hint="preset:rational-blue finance data",
        style_recipe="sharp",
        theme_hint={"primary": "1B2A4A", "secondary": "345A8A", "accent": "4DA3FF", "light": "E7EEF8", "bg": "F5F8FD"},
        layout_family="analytic-blueprint",
        layout_pool_by_page_type=_POOL_RESEARCH,
        layout_weights_by_page_type=_layout_weights(
            _POOL_RESEARCH,
            content={
                "content-stat-callout": 4,
                "content-two-column": 3,
                "content-comparison": 2,
                "content-timeline": 2,
            },
            toc={"toc-grid": 3, "toc-list": 2, "toc-sidebar": 2},
        ),
        typography_profile={"title_font": "Cambria", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="tech-clean",
        decoration_policy="subtle-tech-lines",
        visual_strategy_profile="analysis-first",
        tone_keywords=("rational", "tech", "analysis"),
    ),
    _make_dna(
        style_id="warm-vc",
        name="暖调创投",
        prompt="暖调创投风格，商业质感与亲和力并存，适合路演提案。",
        template_style_hint="preset:warm-vc marketing rounded",
        style_recipe="rounded",
        theme_hint={"primary": "4A2E22", "secondary": "7A4F3A", "accent": "F28C52", "light": "F9E7DA", "bg": "FFF9F4"},
        layout_family="pitch-narrative",
        layout_pool_by_page_type=_POOL_GRID_FORMAL,
        layout_weights_by_page_type=_layout_weights(
            _POOL_GRID_FORMAL,
            content={
                "content-showcase": 4,
                "content-two-column": 3,
                "content-stat-callout": 2,
                "content-comparison": 2,
            },
            summary={"summary-cta": 4, "summary-takeaways": 2, "summary-split": 2},
        ),
        typography_profile={"title_font": "Trebuchet MS", "body_font": "Calibri"},
        density_profile="balanced",
        shape_language="rounded-card",
        decoration_policy="warm-gradient",
        visual_strategy_profile="narrative-callout",
        tone_keywords=("vc", "pitch", "brand"),
    ),
    _make_dna(
        style_id="contemporary-academic",
        name="当代学术",
        prompt="当代学术风格，现代简洁，研究展板式信息组织。",
        template_style_hint="preset:contemporary-academic report authority",
        style_recipe="sharp",
        theme_hint={"primary": "1E2430", "secondary": "4A5568", "accent": "6B8AF5", "light": "E8EBF2", "bg": "FAFBFD"},
        layout_family="poster-research",
        layout_pool_by_page_type=_POOL_RESEARCH,
        layout_weights_by_page_type=_layout_weights(
            _POOL_RESEARCH,
            content={
                "content-stat-callout": 3,
                "content-two-column": 3,
                "content-comparison": 3,
                "content-timeline": 2,
            },
            section={"section-center": 2, "section-accent-block": 2},
        ),
        typography_profile={"title_font": "Georgia", "body_font": "Calibri"},
        density_profile="dense",
        shape_language="fine-lines",
        decoration_policy="exhibition-tags",
        visual_strategy_profile="concept-structure",
        tone_keywords=("contemporary", "academic", "poster"),
    ),
    _make_dna(
        style_id="academic-curation",
        name="学术策展",
        prompt="学术策展风格，轻盈克制、展签式排版，强调图文并置。",
        template_style_hint="preset:academic-curation education",
        style_recipe="soft",
        theme_hint={"primary": "2F3542", "secondary": "57606F", "accent": "70A1FF", "light": "EAF0F6", "bg": "FCFDFF"},
        layout_family="curation-caption",
        layout_pool_by_page_type=_POOL_NARRATIVE,
        layout_weights_by_page_type=_layout_weights(
            _POOL_NARRATIVE,
            content={
                "content-showcase": 3,
                "content-two-column": 2,
                "content-icon-rows": 2,
                "content-timeline": 3,
            },
            toc={"toc-list": 3, "toc-cards": 2, "toc-sidebar": 1},
        ),
        typography_profile={"title_font": "Palatino Linotype", "body_font": "Garamond"},
        density_profile="balanced",
        shape_language="caption-light",
        decoration_policy="label-system",
        visual_strategy_profile="image-text-pair",
        tone_keywords=("curation", "exhibition", "culture"),
    ),
)
